-- Update script for user settings
-- Generated by GitHub Copilot on 2025-11-24
-- Purpose: Reset all user settings to standard defaults, pointing to the central server.
-- Note: DataGridView settings are excluded to allow the application to generate them dynamically.

-- 1. Update Production Database (mtm_wip_application_winforms)
UPDATE mtm_wip_application_winforms.usr_settings
SET SettingsJson = '{
    "Theme_Name": "Arctic",
    "WIPDatabase": "mtm_wip_application_winforms",
    "WipServerPort": "3306",
    "AutoExpandPanels": "False",
    "WipServerAddress": "172.16.1.104",
    "AnimationsEnabled": "false",
    "ShowTotalSummaryPanel": "true"
}'
WHERE UserId NOT IN ('JOHNK');

-- 2. Update Test Database (mtm_wip_application_winforms_test)
-- Note: We keep the WIPDatabase pointing to the production name as requested by "proper defaults",
-- unless the application uses this to self-identify, in which case this might need to be changed to _test.
-- Assuming "proper defaults" means the standard configuration.
UPDATE mtm_wip_application_winforms_test.usr_settings
SET SettingsJson = '{
    "Theme_Name": "Arctic",
    "WIPDatabase": "mtm_wip_application_winforms",
    "WipServerPort": "3306",
    "AutoExpandPanels": "False",
    "WipServerAddress": "172.16.1.104",
    "AnimationsEnabled": "false",
    "ShowTotalSummaryPanel": "true"
}'
WHERE UserId NOT IN ('JOHNK');
