CREATE TABLE IF NOT EXISTS `WindowFormMapping` (
  `MappingID` INT NOT NULL AUTO_INCREMENT,
  `CodebaseName` VARCHAR(100) NOT NULL,
  `UserFriendlyName` VARCHAR(100) NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `CreatedDateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastModifiedDateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`MappingID`),
  UNIQUE INDEX `IX_WindowFormMapping_CodebaseName` (`CodebaseName` ASC)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;
