CREATE TABLE IF NOT EXISTS `EmailNotificationConfig` (
  `ConfigID` INT NOT NULL AUTO_INCREMENT,
  `FeedbackCategory` VARCHAR(100) NOT NULL,
  `RecipientEmails` TEXT NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `CreatedDateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastModifiedDateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ConfigID`),
  UNIQUE INDEX `IX_EmailNotificationConfig_Category` (`FeedbackCategory` ASC)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;
