using System;

namespace MTM_WIP_Application_WinForms.Models;

/// <summary>
/// Represents an error report submitted by a user with optional contextual notes.
/// Maps to error_reports database table.
/// </summary>
public class Model_ErrorReport_Core
{
    #region Properties

    /// <summary>
    /// Unique identifier for the error report (auto-generated by database).
    /// </summary>
    public int ReportID { get; set; }

    /// <summary>
    /// Timestamp when the error occurred and report was created.
    /// Defaults to current UTC time.
    /// </summary>
    public DateTime ReportDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Windows username of the user who encountered the error (required).
    /// Example: "John.Smith"
    /// </summary>
    public string UserName { get; set; } = string.Empty;

    /// <summary>
    /// Computer name where the error occurred.
    /// Example: "DESKTOP-ABC123", "WORKSTATION-42"
    /// </summary>
    public string? MachineName { get; set; }

    /// <summary>
    /// Application version at the time of the error.
    /// Example: "5.0.0.142"
    /// </summary>
    public string? AppVersion { get; set; }

    /// <summary>
    /// Exception type name.
    /// Example: "NullReferenceException", "SqlException"
    /// </summary>
    public string? ErrorType { get; set; }

    /// <summary>
    /// User-friendly error message (max 64KB).
    /// This is typically the Exception.Message property.
    /// </summary>
    public string? ErrorSummary { get; set; }

    /// <summary>
    /// User-provided context describing what they were doing when the error occurred.
    /// This is the KEY field for user input from the Report Issue dialog.
    /// Example: "I was clicking the Save button after entering inventory data."
    /// </summary>
    public string? UserNotes { get; set; }

    /// <summary>
    /// Full exception details including inner exceptions.
    /// This is typically the Exception.ToString() output.
    /// </summary>
    public string? TechnicalDetails { get; set; }

    /// <summary>
    /// Complete stack trace at time of error.
    /// This is typically the Exception.StackTrace property.
    /// </summary>
    public string? CallStack { get; set; }

    /// <summary>
    /// Lifecycle status of the error report.
    /// </summary>
    public ErrorReportStatus Status { get; set; } = ErrorReportStatus.New;

    /// <summary>
    /// Developer username who reviewed the report.
    /// Set when Status changes to Reviewed or Resolved.
    /// </summary>
    public string? ReviewedBy { get; set; }

    /// <summary>
    /// Timestamp when report was marked as Reviewed.
    /// </summary>
    public DateTime? ReviewedDate { get; set; }

    /// <summary>
    /// Internal notes from developers about resolution.
    /// Used for tracking fixes and workarounds.
    /// </summary>
    public string? DeveloperNotes { get; set; }

    #endregion
}

/// <summary>
/// Represents the lifecycle status of an error report.
/// </summary>
public enum ErrorReportStatus
{
    /// <summary>
    /// Report has been submitted but not yet reviewed by a developer.
    /// </summary>
    New,

    /// <summary>
    /// Report has been reviewed by a developer.
    /// </summary>
    Reviewed,

    /// <summary>
    /// Issue has been fixed and verified.
    /// </summary>
    Resolved
}
